%% Creazione del file
fileID = fopen('log_file.txt','w');
fprintf(fileID,'%s %s %s %s %s %s %s %s %s %s %s \r\n','matrix,', ...
'dimensions,', 'type,', 'iter,', 'time_mean,', 'time_var,', ...
'used_memory,', 'rel_error,', 'system,', ...
'language,', 'library');
fclose(fileID);